#!/bin/bash

export PS4='+${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}():} '

# TODO: Randomize the exposed port

readonly name=exclusive-arc-sql-example
# shellcheck disable=SC2209
readonly user=test
# shellcheck disable=SC2209
readonly pass=test

print_usage() {
    echo "Usage: ${0##*/} [-f]"
}

print_help() {
    cat <<EOH

Starts Postgres in the background, runs examples, and shuts Postgres down.

Options:
   -f   starts Postgres in the foreground; does not run examples; SIGINT to quit
   -h   prints this help and exits
EOH
}

foreground=false
while getopts :fh opt; do
    case $opt in
    f) foreground=true ;;
    h)
        print_usage
        print_help
        exit 0
        ;;
    *)
        print_usage >&2
        exit 2
        ;;
    esac
done
shift $((OPTIND - 1))
case $# in
0) ;;
*)
    print_usage >&2
    exit 2
    ;;
esac

postgres() {
    docker run \
        --name "$name" \
        "$@" \
        --rm \
        -p 5432:5432 \
        -e POSTGRES_USER="$user" -e POSTGRES_PASSWORD="$pass" \
        -v "$PWD"/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d \
        --mount type=tmpfs,destination=/var/lib/postgresql/data \
        postgres:16.0-alpine \
        -c fsync=off
}

if $foreground; then
    postgres
    exit $?
fi

postgres -d >/dev/null

# TODO: This does not actually always work :(
sleep 1
while ! docker exec "$name" pg_isready -q -d "$user" -U "$user"; do
    sleep 1
done

echo "Raw data ('quotation_p'):"
docker exec -i "$name" psql -n -U "$user" <<EOSQL
SELECT *
FROM quotation_p;
EOSQL

echo "User view ('quotation'):"
docker exec -i "$name" psql -n -U "$user" <<EOSQL
SELECT *
FROM quotation;
EOSQL

echo "User view ('quotation_expanded'):"
docker exec -i "$name" psql -n -U "$user" <<EOSQL
SELECT *
FROM quotation_expanded;
EOSQL

echo "User view ('word'):"
docker exec -i "$name" psql -n -U "$user" <<EOSQL
SELECT *
FROM word;
EOSQL

echo "User view ('phrase'):"
docker exec -i "$name" psql -n -U "$user" <<EOSQL
SELECT *
FROM phrase;
EOSQL

echo "User view ('sentence'):"
docker exec -i "$name" psql -n -U "$user" <<EOSQL
SELECT *
FROM sentence;
EOSQL

echo "User view ('paragraph'):"
docker exec -i "$name" psql -n -U "$user" <<EOSQL
SELECT *
FROM paragraph;
EOSQL

docker exec "$name" kill -TERM 1
